environ
    vocabularies XBOOLE_0, TARSKI;
    notations TARSKI, XBOOLE_0;
    constructors TARSKI, XBOOLE_0;
    definitions XBOOLE_0, TARSKI;
    equalities XBOOLE_0;
    expansions TARSKI;
    theorems XBOOLE_0, TARSKI;

begin

theorem
    for X being set holds X \ {} = X
proof
    let X be set;
    thus X \ {} c= X
    by XBOOLE_0:def 5;
    let x be object;
A1: not x in {} by XBOOLE_0:def 5;
    assume x in X;
    hence thesis by A1,XBOOLE_0:def 5;
end;